In [3]:
import pandas as pd
import numpy as np
import polars as pl
import yaml

In [4]:
with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)

In [5]:
df = pl.read_csv(config["input_data"]["file_1"])
df

shape: (1_083_397, 42)
┌──────────────┬─────────────┬─────────────┬─────────┬───┬─────────┬───────┬────────────┬──────────┐
│ restaurant_l ┆ restaurant_ ┆ original_lo ┆ country ┆ … ┆ service ┆ value ┆ atmosphere ┆ keywords │
│ ink          ┆ name        ┆ cation      ┆ ---     ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---      │
│ ---          ┆ ---         ┆ ---         ┆ str     ┆   ┆ f64     ┆ f64   ┆ f64        ┆ str      │
│ str          ┆ str         ┆ str         ┆         ┆   ┆         ┆       ┆            ┆          │
╞══════════════╪═════════════╪═════════════╪═════════╪═══╪═════════╪═══════╪════════════╪══════════╡
│ g10001637-d1 ┆ Le 147      ┆ ["Europe",  ┆ France  ┆ … ┆ 4.5     ┆ 4.0   ┆ null       ┆ null     │
│ 0002227      ┆             ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Nouvelle…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10001637-d1 ┆ Le Saint    ┆ ["Europe",  ┆ France  ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 4975787      ┆ Jouvent     ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Nouvelle…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10002858-d4 ┆ Au Bout du  ┆ ["Europe",  ┆ France  ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 586832       ┆ Pont        ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Centre-V…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10002986-d3 ┆ Le Relais   ┆ ["Europe",  ┆ France  ┆ … ┆ 4.5     ┆ 4.5   ┆ null       ┆ null     │
│ 510044       ┆ de Naiade   ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Nouvelle…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10022428-d9 ┆ Relais Du   ┆ ["Europe",  ┆ France  ┆ … ┆ 4.5     ┆ 4.5   ┆ null       ┆ null     │
│ 767191       ┆ MontSeigne  ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Occitani…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ …            ┆ …           ┆ …           ┆ …       ┆ … ┆ …       ┆ …     ┆ …          ┆ …        │
│ g9710275-d10 ┆ Complex     ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 770782       ┆ Popas       ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆ Pacurari    ┆ "Northea…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9716321-d15 ┆ Casa Pastra ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 026574       ┆ varului     ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆ DORIPESCO   ┆ "Transyl…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9722813-d15 ┆ Hanul       ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 891057       ┆ Tentea      ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Transyl…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9726871-d21 ┆ Casa        ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 391722       ┆ Paduraru    ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Souther…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9867250-d14 ┆ Pastravaria ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 979687       ┆ Alina Sarbi ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Transyl…   ┆         ┆   ┆         ┆       ┆            ┆          │
└──────────────┴─────────────┴─────────────┴─────────┴───┴─────────┴───────┴────────────┴──────────┘

In [6]:
# filter by country Spain
df_spain = df.filter(pl.col("country") == "Spain")
df_spain

shape: (157_479, 42)
┌──────────────┬─────────────┬─────────────┬─────────┬───┬─────────┬───────┬────────────┬──────────┐
│ restaurant_l ┆ restaurant_ ┆ original_lo ┆ country ┆ … ┆ service ┆ value ┆ atmosphere ┆ keywords │
│ ink          ┆ name        ┆ cation      ┆ ---     ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---      │
│ ---          ┆ ---         ┆ ---         ┆ str     ┆   ┆ f64     ┆ f64   ┆ f64        ┆ str      │
│ str          ┆ str         ┆ str         ┆         ┆   ┆         ┆       ┆            ┆          │
╞══════════════╪═════════════╪═════════════╪═════════╪═══╪═════════╪═══════╪════════════╪══════════╡
│ g10021880-d1 ┆ Taberna La  ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 3763192      ┆ Sacristia   ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ Tasca el    ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 5758746      ┆ Capricho    ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ Bar Las     ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 9332558      ┆ Adelfas     ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ El Rincon   ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 9468788      ┆ nº 7        ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ Nuevo       ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 9847377      ┆ jacaranda   ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ …            ┆ …           ┆ …           ┆ …       ┆ … ┆ …       ┆ …     ┆ …          ┆ …        │
│ g9871604-d13 ┆ Mesón La    ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 931661       ┆ Parrillada  ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9871604-d87 ┆ Restaurante ┆ ["Europe",  ┆ Spain   ┆ … ┆ 4.0     ┆ 4.0   ┆ null       ┆ null     │
│ 38469        ┆ La Paz      ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9871604-d98 ┆ Parrillada  ┆ ["Europe",  ┆ Spain   ┆ … ┆ 4.0     ┆ 4.0   ┆ null       ┆ null     │
│ 12919        ┆ Barral      ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9871607-d20 ┆ BP          ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 375801       ┆             ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9984094-d15 ┆ Restaurante ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 652066       ┆ Fito Mar    ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Asturias"… ┆         ┆   ┆         ┆       ┆            ┆          │
└──────────────┴─────────────┴─────────────┴─────────┴───┴─────────┴───────┴────────────┴──────────┘