In [2]:
import pandas as pd
import numpy as np
import polars as pl
import yaml

In [3]:
with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)

In [22]:
df1 = pl.read_csv(config["input_data"]["file_1"])
df1

shape: (1_083_397, 42)
┌──────────────┬─────────────┬─────────────┬─────────┬───┬─────────┬───────┬────────────┬──────────┐
│ restaurant_l ┆ restaurant_ ┆ original_lo ┆ country ┆ … ┆ service ┆ value ┆ atmosphere ┆ keywords │
│ ink          ┆ name        ┆ cation      ┆ ---     ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---      │
│ ---          ┆ ---         ┆ ---         ┆ str     ┆   ┆ f64     ┆ f64   ┆ f64        ┆ str      │
│ str          ┆ str         ┆ str         ┆         ┆   ┆         ┆       ┆            ┆          │
╞══════════════╪═════════════╪═════════════╪═════════╪═══╪═════════╪═══════╪════════════╪══════════╡
│ g10001637-d1 ┆ Le 147      ┆ ["Europe",  ┆ France  ┆ … ┆ 4.5     ┆ 4.0   ┆ null       ┆ null     │
│ 0002227      ┆             ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Nouvelle…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10001637-d1 ┆ Le Saint    ┆ ["Europe",  ┆ France  ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 4975787      ┆ Jouvent     ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Nouvelle…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10002858-d4 ┆ Au Bout du  ┆ ["Europe",  ┆ France  ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 586832       ┆ Pont        ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Centre-V…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10002986-d3 ┆ Le Relais   ┆ ["Europe",  ┆ France  ┆ … ┆ 4.5     ┆ 4.5   ┆ null       ┆ null     │
│ 510044       ┆ de Naiade   ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Nouvelle…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10022428-d9 ┆ Relais Du   ┆ ["Europe",  ┆ France  ┆ … ┆ 4.5     ┆ 4.5   ┆ null       ┆ null     │
│ 767191       ┆ MontSeigne  ┆ "France",   ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Occitani…  ┆         ┆   ┆         ┆       ┆            ┆          │
│ …            ┆ …           ┆ …           ┆ …       ┆ … ┆ …       ┆ …     ┆ …          ┆ …        │
│ g9710275-d10 ┆ Complex     ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 770782       ┆ Popas       ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆ Pacurari    ┆ "Northea…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9716321-d15 ┆ Casa Pastra ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 026574       ┆ varului     ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆ DORIPESCO   ┆ "Transyl…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9722813-d15 ┆ Hanul       ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 891057       ┆ Tentea      ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Transyl…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9726871-d21 ┆ Casa        ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 391722       ┆ Paduraru    ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Souther…   ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9867250-d14 ┆ Pastravaria ┆ ["Europe",  ┆ Romania ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 979687       ┆ Alina Sarbi ┆ "Romania",  ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Transyl…   ┆         ┆   ┆         ┆       ┆            ┆          │
└──────────────┴─────────────┴─────────────┴─────────┴───┴─────────┴───────┴────────────┴──────────┘

In [ ]:
# filter by country Spain
df_spain = df1.filter(pl.col("country") == "Spain")
df_spain

shape: (157_479, 42)
┌──────────────┬─────────────┬─────────────┬─────────┬───┬─────────┬───────┬────────────┬──────────┐
│ restaurant_l ┆ restaurant_ ┆ original_lo ┆ country ┆ … ┆ service ┆ value ┆ atmosphere ┆ keywords │
│ ink          ┆ name        ┆ cation      ┆ ---     ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---      │
│ ---          ┆ ---         ┆ ---         ┆ str     ┆   ┆ f64     ┆ f64   ┆ f64        ┆ str      │
│ str          ┆ str         ┆ str         ┆         ┆   ┆         ┆       ┆            ┆          │
╞══════════════╪═════════════╪═════════════╪═════════╪═══╪═════════╪═══════╪════════════╪══════════╡
│ g10021880-d1 ┆ Taberna La  ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 3763192      ┆ Sacristia   ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ Tasca el    ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 5758746      ┆ Capricho    ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ Bar Las     ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 9332558      ┆ Adelfas     ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ El Rincon   ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 9468788      ┆ nº 7        ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g10021880-d1 ┆ Nuevo       ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 9847377      ┆ jacaranda   ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Andalucia… ┆         ┆   ┆         ┆       ┆            ┆          │
│ …            ┆ …           ┆ …           ┆ …       ┆ … ┆ …       ┆ …     ┆ …          ┆ …        │
│ g9871604-d13 ┆ Mesón La    ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 931661       ┆ Parrillada  ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9871604-d87 ┆ Restaurante ┆ ["Europe",  ┆ Spain   ┆ … ┆ 4.0     ┆ 4.0   ┆ null       ┆ null     │
│ 38469        ┆ La Paz      ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9871604-d98 ┆ Parrillada  ┆ ["Europe",  ┆ Spain   ┆ … ┆ 4.0     ┆ 4.0   ┆ null       ┆ null     │
│ 12919        ┆ Barral      ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9871607-d20 ┆ BP          ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 375801       ┆             ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Galicia",… ┆         ┆   ┆         ┆       ┆            ┆          │
│ g9984094-d15 ┆ Restaurante ┆ ["Europe",  ┆ Spain   ┆ … ┆ null    ┆ null  ┆ null       ┆ null     │
│ 652066       ┆ Fito Mar    ┆ "Spain",    ┆         ┆   ┆         ┆       ┆            ┆          │
│              ┆             ┆ "Asturias"… ┆         ┆   ┆         ┆       ┆            ┆          │
└──────────────┴─────────────┴─────────────┴─────────┴───┴─────────┴───────┴────────────┴──────────┘

In [26]:
# save the filtered dataframe to a new csv file
df_spain.write_csv("../data/processed/tripadvisor_spain.csv.gz")

InvalidOperationError: use the compression parameter to control compression, or set `check_extension` to `False` if you want to suffix an uncompressed filename with an ending intended for compression

Resolved plan until failure:

	---> FAILED HERE RESOLVING THIS_NODE <---
DF ["restaurant_link", "restaurant_name", "original_location", "country", ...]; PROJECT */42 COLUMNS

In [12]:
# check who has the most reviews in Spain
df_spain_reviews = df_spain.group_by("restaurant_name").agg(pl.col("total_reviews_count"))
df_spain_reviews.sort("total_reviews_count", descending=True)

shape: (134_666, 2)
┌─────────────────────────────────┬─────────────────────┐
│ restaurant_name                 ┆ total_reviews_count │
│ ---                             ┆ ---                 │
│ str                             ┆ list[f64]           │
╞═════════════════════════════════╪═════════════════════╡
│ Mercado de San Miguel           ┆ [33731.0]           │
│ Chocolatería San Ginés          ┆ [22364.0]           │
│ El Pimpi                        ┆ [14823.0]           │
│ Cervecería Catalana             ┆ [12635.0]           │
│ San Tommaso                     ┆ [10056.0]           │
│ …                               ┆ …                   │
│ Alex of Madrid                  ┆ [null]              │
│ Pizza-Kebap                     ┆ [null]              │
│ Fang Wang                       ┆ [null]              │
│ El Ideal Cafeteria Restaurante  ┆ [null]              │
│ Bar Restaurante Orialde, Ochag… ┆ [null]              │
└─────────────────────────────────┴─────────────────────┘

In [13]:
df_spain_reviews = (
    df_spain
    .group_by("restaurant_name")
    .agg(pl.col("total_reviews_count").sum())
    # Filtre: NO sea null i +100 reviews
    .filter(
        pl.col("total_reviews_count").is_not_null() & 
        (pl.col("total_reviews_count") > 100)
    )
    .sort("total_reviews_count", descending=True)
)

print(df_spain_reviews)

shape: (31_971, 2)
┌────────────────────────┬─────────────────────┐
│ restaurant_name        ┆ total_reviews_count │
│ ---                    ┆ ---                 │
│ str                    ┆ f64                 │
╞════════════════════════╪═════════════════════╡
│ Mercado de San Miguel  ┆ 33731.0             │
│ Chocolatería San Ginés ┆ 22364.0             │
│ Hard Rock Cafe         ┆ 20515.0             │
│ El Pimpi               ┆ 14823.0             │
│ Museo del Jamon        ┆ 13047.0             │
│ …                      ┆ …                   │
│ Kruger                 ┆ 101.0               │
│ The Corner Cafe        ┆ 101.0               │
│ Bitadorna              ┆ 101.0               │
│ Alvarez                ┆ 101.0               │
│ La Perdiz de Somontes  ┆ 101.0               │
└────────────────────────┴─────────────────────┘

In [14]:
# check the number of values in the price_level and price_range columns
print(df_spain["price_level"].value_counts())
print(df_spain["price_range"].value_counts())

shape: (4, 2)
┌─────────────┬───────┐
│ price_level ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ €           ┆ 33489 │
│ €€€€        ┆ 3913  │
│ null        ┆ 40671 │
│ €€-€€€      ┆ 79406 │
└─────────────┴───────┘
shape: (2_270, 2)
┌──────────────┬───────┐
│ price_range  ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ €23-€35      ┆ 8     │
│ CHF 4-CHF 44 ┆ 2     │
│ €35-€50      ┆ 39    │
│ €40-€75      ┆ 4     │
│ €18-€32      ┆ 4     │
│ …            ┆ …     │
│ €8-€41       ┆ 20    │
│ €15-€30      ┆ 852   │
│ €25-€67      ┆ 2     │
│ €4-€50       ┆ 37    │
│ CHF 2-CHF 17 ┆ 8     │
└──────────────┴───────┘

In [21]:
# check how many restaurants have a price_range greater than 12€
df_spain_price_range = df_spain.filter(pl.col("price_range") > "€12")
df_spain_price_range.count()

shape: (1, 42)
┌──────────────┬─────────────┬─────────────┬─────────┬───┬─────────┬───────┬────────────┬──────────┐
│ restaurant_l ┆ restaurant_ ┆ original_lo ┆ country ┆ … ┆ service ┆ value ┆ atmosphere ┆ keywords │
│ ink          ┆ name        ┆ cation      ┆ ---     ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---      │
│ ---          ┆ ---         ┆ ---         ┆ u32     ┆   ┆ u32     ┆ u32   ┆ u32        ┆ u32      │
│ u32          ┆ u32         ┆ u32         ┆         ┆   ┆         ┆       ┆            ┆          │
╞══════════════╪═════════════╪═════════════╪═════════╪═══╪═════════╪═══════╪════════════╪══════════╡
│ 39853        ┆ 39853       ┆ 39853       ┆ 39853   ┆ … ┆ 22563   ┆ 22497 ┆ 8389       ┆ 3703     │
└──────────────┴─────────────┴─────────────┴─────────┴───┴─────────┴───────┴────────────┴──────────┘